models:

    - name: mart_attendance
      description: '{{ doc("models_attendance") }}'
      tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - date
              - member_name

      columns:
        - name: date
          description: '{{ doc("date") }}'
        - name: parliament
          description: '{{ doc("parliament") }}'
        - name: session
          description: '{{ doc("session") }}'
        - name: member_name
          description: '{{ doc("member_name") }}'
        - name: member_party
          description: '{{ doc("member_party") }}'
        - name: member_gender
          description: '{{ doc("member_gender") }}'
        - name: is_present
          description: '{{ doc("is_present") }}'

    - name: mart_speeches
      description: '{{ doc("models_speeches") }}'

      columns:
        - name: date
          description: '{{ doc("date") }}'
        - name: speech_id
          description: '{{ doc("speech_id") }}'
          tests:
            - not_null
            - unique
        - name: topic_id
          description: '{{ doc("topic_id") }}'
        - name: parliament
          description: '{{ doc("parliament") }}'
        - name: session
          description: '{{ doc("session") }}'
        - name: volume
          description: '{{ doc("volume") }}'
        - name: sittings
          description: '{{ doc("sittings") }}'
        - name: member_name
          description: '{{ doc("member_name") }}'
        - name: member_party
          description: '{{ doc("member_party") }}'
        - name: member_gender
          description: '{{ doc("member_gender") }}'
        - name: topic_title
          description: '{{ doc("topic_title") }}'
        - name: topic_type
          description: '{{ doc("topic_type") }}'
        - name: topic_type_name
          description: '{{ doc("topic_type") }}'
        - name: is_topic_constitutional
          description: '{{ doc("is_topic_constitutional") }}'
        - name: is_topic_procedural
          description: '{{ doc("is_topic_procedural") }}'
        - name: speech_text
          description: '{{ doc("speech_text") }}'
        - name: count_speeches_words
          description: '{{ doc("count_words") }}'
        - name: count_speeches_characters
          description: '{{ doc("count_characters") }}'
        - name: count_speeches_sentences
          description: '{{ doc("count_sentences") }}'
        - name: count_speeches_syllables
          description: '{{ doc("count_syllables") }}'
        - name: is_short_speech
          description: '{{ doc("is_short_speech") }}'
        - name: is_long_speech
          description: '{{ doc("is_long_speech") }}'
        - name: is_vernacular_speech
          description: '{{ doc("is_vernacular_speech") }}'
        - name: vernacular_speech_language
          description: '{{ doc("vernacular_speech_language") }}'

    - name: mart_bills
      description: '{{ doc("models_bills") }}'
      tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - year
              - title
            config:
              where: bill_number is null

      columns:
        - name: bill_number
          tests:
            - unique
        - name: year
        - name: first_reading_date
        - name: first_reading_topic
        - name: day_diff_first_second_reading
        - name: second_reading_date
        - name: second_reading_topic
        - name: day_diff_second_third_reading
        - name: third_reading_date
        - name: third_reading_topic
        - name: day_diff_third_reading_passed
        - name: passed_date
        - name: bill_pdf_link
